steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/stock-movement-analyzer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/stock-movement-analyzer:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-movement-analyzer:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-movement-analyzer:latest']

options:
  logging: CLOUD_LOGGING_ONLY
