services:
  - type: web
    name: stock-movement-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1 --threads 1
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: DART_API_KEY
        sync: false
      - key: KRX_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: 3.11.11
